image:
- Visual Studio 2017
- Ubuntu1804

branches:
  except:
    - l10n_master
    - gh-pages

services:
- docker

stack: node 10

init:
- ps: |
    if($isWindows) {
      Install-Product node 10
    }

install:
- ps: |
    $env:PACKAGE_VERSION = (Get-Content -Raw -Path .\package.json | ConvertFrom-Json).version
    $env:PUSH_DOCKER = "false"
    $env:PROD_DEPLOY = "false"
    $env:TAG_NAME = ""
    if($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_RE_BUILD -eq "True") {
      $env:PROD_DEPLOY = "true"
      $env:TAG_NAME = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")
      echo "This is a production deployment for ${env:TAG_NAME}."
    }
    if("${env:DOCKER_USERNAME}" -ne "" -and "${env:DOCKER_PASSWORD}" -ne "") {
      $env:PUSH_DOCKER = "true"
    }
    if($isWindows) {
      choco install cloc --no-progress
      cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
    }

before_build:
- node --version
- npm --version
- sh: |
    if [ "${PUSH_DOCKER}" == "true" ]
    then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      mkdir -p ~/.docker/trust/private
      
      echo PATH=$PATH
      echo "------------"
      sudo wget -O /usr/local/bin/notary https://github.com/theupdateframework/notary/releases/download/v0.6.1/notary-Linux-amd64
      sudo chmod +x /usr/local/bin/notary

      # Create Trust Keys (because AppVeyor doesn't support storing them
      # https://www.appveyor.com/docs/how-to/private-git-sub-modules/#ui
      echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.docker/trust/private/$DOCKER_DELEGATION_KEY_ID.key
      echo "role: bitwardenadmin" >> ~/.docker/trust/private/$DOCKER_DELEGATION_KEY_ID.key
      echo "$DOCKER_DELEGATION_KEY" | tr " " "\n" >> ~/.docker/trust/private/$DOCKER_DELEGATION_KEY_ID.key
      echo "-----BEGIN RSA PRIVATE KEY-----" >> ~/.docker/trust/private/$DOCKER_DELEGATION_KEY_ID.key

      echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.docker/trust/private/$DOCKER_REPO_KEY_ID.key
      echo "gun: docker.io/bitwarden/web" >> ~/.docker/trust/private/$DOCKER_REPO_KEY_ID.key
      echo "role: targets" >> ~/.docker/trust/private/$DOCKER_REPO_KEY_ID.key
      echo "$DOCKER_REPO_KEY" | tr " " "\n" >> ~/.docker/trust/private/$DOCKER_REPO_KEY_ID.key
      echo "-----BEGIN RSA PRIVATE KEY-----" >> ~/.docker/trust/private/$DOCKER_REPO_KEY_ID.key

      chmod 600 ~/.docker/trust/private/$DOCKER_DELEGATION_KEY_ID.key
      chmod 600 ~/.docker/trust/private/$DOCKER_REPO_KEY_ID.key

      notary -s https://notary.docker.io -d ~/.docker/trust key list

      #echo "$DOCKER_DELEGATION_PUBLIC_KEY" > ~/bitwardenadmin.pub
      #cat ~/bitwardenadmin.pub
    fi
- cmd: set "GIT_PATH=C:\Program Files\Git\mingw64\libexec\git-core"
- cmd: set "PATH=%GIT_PATH%;%PATH%"

build_script:
- sh: chmod +x ./build.sh
- ps: |
    if($isLinux) {
      ./build.sh
      ./build.sh tag dev

      if($env:PROD_DEPLOY -eq "true") {
        ./build.sh tag beta
        ./build.sh tag $env:TAG_NAME
      }

      docker images
      
      if($env:PUSH_DOCKER -eq "true") {
        $env:DOCKER_CONTENT_TRUST = 1
        ./build.sh push dev

        if($env:PROD_DEPLOY -eq "true") {
          ./build.sh push beta
          ./build.sh push latest
          ./build.sh push $env:TAG_NAME
        }
      }
    }
- cmd: npm install
- cmd: npm run build:prod

after_build:
- sh: |
    if [ "${PUSH_DOCKER}" == "true" ]
    then
      docker logout
    fi
